admin_page_index:
  path: /
  controller: 'SymfonySimpleSite\Page\Controller\AdminController::index'

admin_page_create:
  path: /create
  controller: 'SymfonySimpleSite\Page\Controller\AdminController::save'

admin_page_edit:
  path: /edit/{id}
  controller: 'SymfonySimpleSite\Page\Controller\AdminController::save'

admin_page_delete:
  path: /delete/{id}
  controller: 'SymfonySimpleSite\Page\Controller\AdminController::delete'
