page_main_page:
  path: /
  controller: 'SymfonySimpleSite\Page\Controller\PageController::mainPage'

page_detail:
  path: /page/{url?}
  requirements:
    url: '^([a-z-0-9\.\-\/]+)$'
  controller: 'SymfonySimpleSite\Page\Controller\PageController::detail'
