<?php

namespace SymfonySimpleSite\Page;

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;
use SymfonySimpleSite\Common\Interfaces\BundleInterface;

class PageBundle extends Bundle implements BundleInterface
{
    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub
    }

    public static function getConfigName(): string
    {
        return 'page';
    }
}

